### ISSUE TITLE
Integration with other php codes.

### ISSUE THREAD

**Issue by pureche** [fieu/phust#1]
I'm wondering if you would consider releasing phust in a way that makes it able to be integrated into other php codes. 

The reason I'm asking is because the current way of implementing phust is through exec(), and on some of my servers exec is disabled for security reasons. 

And also because I don't have enough understanding to dig through your source codes to implement it myself... though I know it's possible.

**Comment by fieu** [comment]
Hey @pureche, that's a good proposition, though considering that phust is only an abstraction for the websocket connection, it makes no sense in my mind to make a PHP package for it.

If you're interested in where the magic happens, it's right here: https://github.com/fieu/phust/blob/master/app/Commands/SendRconCommand.php#L49-L58

Let me know if you have any more questions.

**Comment by pureche** [comment]
@fieu Thank you for the reply.

Now I see it. It's way easier than I thought. I thought you needed some obscure protocols to talk to rust rcon servers. 

Thank you for pointing that out for me, really appreciate it.
